
trigger: none

schedules:
  - cron: 0 0 * * 0
    displayName: "Weekly build"
    branches:
      include: [ main ]
    always: true

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-B -Prelease'
      mavenOptions: '-s $(Build.SourcesDirectory)/.devops/settings.xml'
      mavenAuthenticateFeed: true
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
    displayName: 'Build with Maven'
